version: '3.7'
services:
  web:
    # build: .    #Esto crea lo que tenemos localmente
    image: dilverpro/lessa-frontend:v2 #baja la imagen de el hub y lo correo
    command: npm run start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"

# docker-compose up